### ISSUE TITLE
Makefile needs to be updated for gcc 4.8

### ISSUE THREAD

**Issue by michaelveth** [mini-box/dcdc-usb#1]
The compilation object should moved AFTER the linked files on the dcdc-usb: build step.  

e.g.:  Change it to this:

dcdc-usb: $(MAINSRC)
    $(CC) $(CFLAGS) $(MAINSRC) -L. -ldcdc-usb -o $@ $(LIBS)

See my pull request w/ corrected code.

**Comment by nicupavel** [comment]
Ok. I'm willing  to merge if you send a pull request

**Comment by nicupavel** [comment]
Fixed in 3e65959f1663bbe2ff5fefdf81966efdb2993daf
