### ISSUE TITLE
Not working properly on Ubuntu 14.04

### ISSUE THREAD

**Issue by dpiet** [mini-box/dcdc-usb#3]
I'm running into issues trying to use dcdc-usb on Ubuntu Linux. I cloned the repository and it built fine but wasn't able to run the application successfully.

This is what I get:
$ dcdc-usb 
Cannot set configuration 1 for the device
Cannot setup device

After getting this I modified the dcdc-usb-comm.c file to print the error code for the usb_set_configuration() call. It returned -1, and in libusb it looks like that's an IO error.

Can you provide some guidance here?
System specs:
Ubuntu 14.04.2
Kernel 3.16.0-52
libusb 0.1
Note that I tried building with libusb-1.0 and ran into build issues which could be associated with my system. Can you confirm version dependency on libusb?

**Comment by Myzhar** [comment]
I was going to open the same issue. I get the same error on Nvidia Jetson TX1, while on my laptop the same code works without any issue

**Comment by dpiet** [comment]
@Myzhar May I ask what your laptop setup is? Libusb version?

**Comment by Myzhar** [comment]
This is my current configuration for libusb libraries:
![libusb](https://cloud.githubusercontent.com/assets/3648617/14077325/c3f3f1d0-f4ea-11e5-9d8b-b57ec594cf1c.png)

**Comment by maciekd** [comment]
I'm having the same issue.

**Comment by maciekd** [comment]
I’ve investigated this a bit further.

I rewrote the entire program from scratch using libusb 1.0 (instead of 0.1) but I get exactly the same error (as noted in the github issue below).

It seems this is a problem with the USB comm. on OS level. I looked through my system messages and saw:

> [ 2542.454306] hub 2-1.1:1.0: USB hub found
> [ 2542.454647] hub 2-1.1:1.0: 4 ports detected
> [ 2542.544355] usb 2-1.3: new full-speed USB device number 16 using xhci_hcd
> [ 2542.648232] usb 2-1.3: New USB device found, idVendor=04d8, idProduct=d003
> [ 2542.648234] usb 2-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [ 2542.648236] usb 2-1.3: Product: DCDC-USB
> [ 2542.648237] usb 2-1.3: Manufacturer: MINI-BOX.COM
> [ 2542.648238] usb 2-1.3: SerialNumber: 1.00rel.
> [ 2542.648321] usb 2-1.3: ep 0x1 - rounding interval to 64 microframes, ep desc says 80 microframes
> **[ 2547.651199] usbhid 2-1.3:1.0: can't add hid device: -32**
> **[ 2547.651271] usbhid: probe of 2-1.3:1.0 failed with error -32**

I’m really at a loss here. Any help at all would be appreciated.

**Comment by maciekd** [comment]
Problem might be related to usb3.0 ports. I got the device to (sometimes) work when I put an old USB 2 hub in between.

In this setup the device works sporadically.

**Comment by blgantner** [comment]
Same problem here as well.  Tried on both a desktop (ubuntu 16.04) and raspberry pi (raspbian jessie) and got the exact same error:

$ dcdc-usb
Cannot set configuration 1 for the device
Cannot setup device

Seems to set up fine on the system for me:
[ 2333.473259] usb 3-2: new full-speed USB device number 3 using xhci_hcd
[ 2333.616759] usb 3-2: New USB device found, idVendor=04d8, idProduct=d003
[ 2333.616761] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2333.616763] usb 3-2: Product: DCDC-USB
[ 2333.616765] usb 3-2: Manufacturer: MINI-BOX.COM
[ 2333.616766] usb 3-2: SerialNumber: 1.00rel.
[ 2338.699284] input: MINI-BOX.COM DCDC-USB as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/0003:04D8:D003.0007/input/input18
[ 2338.757774] hid-generic 0003:04D8:D003.0007: input,hiddev0,hidraw3: USB HID v1.01 Device [MINI-BOX.COM DCDC-USB] on usb-0000:00:14.0-2/input0

Tried both the USB 2.0 and 3.0 ports, no difference.  Not to mention that the Pi only have 2.0 ports, so I'm thinking that is not the problem for me at least.  I also booted up the Win10 computer and downloaded their GUI software, worked fine over there.

If anyone found a solution or a work around, I would really appreciate it.

**Comment by Myzhar** [comment]
Have you tried as super-user?
`$ sudo dcdc-usb`

I have written a driver for ROS for DCDC-USB: 
https://github.com/Myzhar/ros_dcdc_usb

a user solved the problem and sent me an email to explained me how to fix the issue:

> I had located the problem and fix it, is very simple as I suspected the issue was permissions at the library to open the device to read status
> 
> so what I did was
> 
> 1.) chmod 0666 /dev/hidraw2 (this is what my dcdc-usb is named in the /dev
> 2.) crate a rule in /etc/udev/rules.d
>      I create my file called 40-dcdc-usb.rules
>     
> SUBSYSTEM=="usb", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="d003", GROUP="ubuntu", MODE="066"
> SUBSYSTEM=="usb_DEVICE", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="d003", GROUP="ubuntu", MODE="066"
> 
> I did also crate some rules for hidraw and hiddev0 with MODE="0666" but not sure if those work
> 
> 
> but now is working and I have tested and reboot several time

**Comment by blgantner** [comment]
Brilliant!  Thanks.  The sudo worked and I'll give the permissions/rules solution a try tonight.  Thanks for the help.

**Comment by Myzhar** [comment]
You are welcome 👍
